### ISSUE TITLE
「ニコニコ動画」関連コードを除去する

### ISSUE THREAD

**Issue by tottokotkd** [tdenc/TDEnc2#1]
* ドワンゴ社自身が動画投稿について対応し始めており、TDEnc2による対応は不要である
* ニコニコ動画のエンコード関連情報は変更実装終了まで「突入負荷対策」の名の下に隠蔽されており、OSSによって対応不能である
* その他諸般の事情を考慮するとコード除去が適切かつ妥当

https://twitter.com/nico_nico_talk/status/988693641446047744

**Comment by tdenc** [comment]
TDEnc2の開発自体おしまいにしたのでこの件はこれでおしまい。
